language: generic 

sudo: required
services:
   - docker

before_install:
   - docker build -t img-docker-react -f DockerFile.dev .

script:     
   - docker run -e CI=true mg-docker-react npm run test
    
